In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("northwind.db")

In [3]:
tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

tables

                    name
0             Categories
1        sqlite_sequence
2   CustomerCustomerDemo
3   CustomerDemographics
4              Customers
5              Employees
6    EmployeeTerritories
7          Order Details
8                 Orders
9               Products
10               Regions
11              Shippers
12             Suppliers
13           Territories

In [4]:
query1 = """
SELECT
    p.ProductName,
    SUM(od.Quantity) AS Total_Quantity_Sold
FROM Products p
JOIN "Order Details" od
ON p.ProductID = od.ProductID
GROUP BY p.ProductID
ORDER BY Total_Quantity_Sold DESC
LIMIT 10;
"""

top_products = pd.read_sql(query1, conn)

top_products

                       ProductName  Total_Quantity_Sold
0        Louisiana Hot Spiced Okra               206213
1           Sir Rodney's Marmalade               205637
2       Teatime Chocolate Biscuits               205487
3                   Sirop d'érable               205005
4              Gumbär Gummibärchen               204761
5                    Outback Lager               204403
6                   Ravioli Angelo               204251
7             Raclette Courdavault               204137
8  Uncle Bob's Organic Dried Pears               203970
9                    Sasquatch Ale               203667

In [5]:
top_products.shape

(10, 2)

In [7]:
top_products.dtypes

ProductName            object
Total_Quantity_Sold     int64
dtype: object

In [8]:
top_products.describe()

       Total_Quantity_Sold
count            10.000000
mean         204753.100000
std             820.692452
min          203667.000000
25%          204165.500000
50%          204582.000000
75%          205366.500000
max          206213.000000

In [9]:
query2 = """
SELECT
    c.CompanyName,
    ROUND(SUM(od.UnitPrice * od.Quantity * (1-od.Discount)),2) AS Revenue
FROM Customers c
JOIN Orders o
ON c.CustomerID=o.CustomerID
JOIN "Order Details" od
ON o.OrderID=od.OrderID
GROUP BY c.CustomerID
ORDER BY Revenue DESC
LIMIT 10;
"""

top_customers = pd.read_sql(query2, conn)

top_customers

                          CompanyName     Revenue
0                       B's Beverages  6154115.34
1          Hungry Coyote Import Store  5698023.67
2                       Rancho grande  5559110.08
3                 Gourmet Lanchonetes  5552309.80
4  Ana Trujillo Emparedados y helados  5534356.65
5                  Ricardo Adocicados  5524517.31
6                   Folies gourmandes  5505502.85
7                   Let's Stop N Shop  5462198.02
8                   LILA-Supermercado  5437438.34
9              Princesa Isabel Vinhos  5436770.55

In [10]:

query3 = """
SELECT
    strftime('%Y-%m',o.OrderDate) AS Month,
    ROUND(SUM(od.UnitPrice*od.Quantity*(1-od.Discount)),2) AS MonthlySales
FROM Orders o
JOIN "Order Details" od
ON o.OrderID=od.OrderID
GROUP BY Month
ORDER BY Month;
"""

monthly_sales = pd.read_sql(query3, conn)

monthly_sales

       Month  MonthlySales
0    2012-07    2066219.40
1    2012-08    3556875.79
2    2012-09    3440144.98
3    2012-10    3201529.96
4    2012-11    2980494.74
..       ...           ...
131  2023-06    3071787.73
132  2023-07    3350337.36
133  2023-08    3293158.67
134  2023-09    3544698.51
135  2023-10    2923364.35

[136 rows x 2 columns]

In [11]:
query4 = """
SELECT
    c.CategoryName,
    ROUND(SUM(od.UnitPrice*od.Quantity*(1-od.Discount)),2) AS Revenue
FROM Categories c
JOIN Products p
ON c.CategoryID=p.CategoryID
JOIN "Order Details" od
ON p.ProductID=od.ProductID
GROUP BY c.CategoryID
ORDER BY Revenue DESC;
"""

category_sales = pd.read_sql(query4, conn)

category_sales

     CategoryName      Revenue
0       Beverages  92163184.18
1     Confections  66337803.06
2    Meat/Poultry  64881147.97
3  Dairy Products  58018116.78
4      Condiments  55795126.78
5         Seafood  49921604.17
6         Produce  32701119.88
7  Grains/Cereals  28568530.34

In [15]:
query5 = """
SELECT
    c.CompanyName,
    COUNT(o.OrderID) AS NumberOfOrders
FROM Customers c
JOIN Orders o
ON c.CustomerID=o.CustomerID
GROUP BY c.CustomerID
ORDER BY NumberOfOrders DESC;
"""

purchase_frequency = pd.read_sql(query5, conn)

purchase_frequency

                             CompanyName  NumberOfOrders
0                          B's Beverages             210
1                     Ricardo Adocicados             203
2                      LILA-Supermercado             203
3                    Gourmet Lanchonetes             202
4                 Princesa Isabel Vinhos             200
..                                   ...             ...
88                       Around the Horn             156
89                  La corne d'abondance             155
90        Furia Bacalhau e Frutos do Mar             155
91  FISSA Fabrica Inter. Salchichas S.A.             155
92                Océano Atlántico Ltda.             154

[93 rows x 2 columns]

In [16]:
print(top_products.isnull().sum())

ProductName            0
Total_Quantity_Sold    0
dtype: int64

In [17]:
print(top_customers.isnull().sum())

CompanyName    0
Revenue        0
dtype: int64

In [18]:
print(monthly_sales.isnull().sum())

Month           0
MonthlySales    0
dtype: int64

In [19]:
print(category_sales.isnull().sum())

CategoryName    0
Revenue         0
dtype: int64

In [20]:
print(purchase_frequency.isnull().sum())

CompanyName       0
NumberOfOrders    0
dtype: int64

Top Products Shape: (10, 2)
       Total_Quantity_Sold
count            10.000000
mean         204753.100000
std             820.692452
min          203667.000000
25%          204165.500000
50%          204582.000000
75%          205366.500000
max          206213.000000